# Generated by Django 2.1.4 on 2018-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='math',
            old_name='wynik',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='math',
            old_name='operacja',
            new_name='calculate',
        ),
        migrations.AddField(
            model_name='math',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
